name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests and Generate Cucumber Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 with Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Verify Maven Installation
        run: |
          mvn -version
          which mvn

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}

      - name: Run Tests
        run: |
          chmod +x mvnw
          ./mvnw clean test -Dgroups="regression" -Dbrowser="chrome" -Dheadless
          echo "Test execution finished with exit code $?"

      - name: Upload Cucumber Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports

      - name: Display Cucumber Report Path
        run: echo "Cucumber Report is available in the CI/CD artifacts."
